export type Exercise = {
  key: string
  name: string
  quip: string            // one-liner shown under name, humor, no emojis
  equipment: 'cable' | 'kettlebell' | 'dumbbell' | 'machine' | 'bodyweight'
  muscles: string[]       // e.g. ['core','obliques']
  cues: string[]          // 3-5 big-print form steps
  mistakes: string[]      // 2-3 common mistakes
  safety: string          // senior-friendly variant / caution
  video: string | null    // curated YouTube URL or null
  defaults: { sets: number; reps: number; weight: number | null }
  unit: 'lb' | 'steps' | 'seconds' | null   // null = bodyweight reps
}

export const EXERCISES: Record<string, Exercise> = {
  // ---------------- CORE ----------------
  cable_wood_chop: {
    key: 'cable_wood_chop',
    name: 'Cable Wood Chop',
    quip: 'Chop wood. There is no wood. Chop anyway.',
    equipment: 'cable',
    muscles: ['core', 'obliques'],
    cues: [
      'Set the cable handle at shoulder height.',
      'Stand sideways to the machine, feet wide.',
      'Pull the handle across your body, down toward the opposite hip.',
      'Turn your hips and shoulders together — like swinging a golf club.',
      'Control it back up slowly. Slow is strong.',
    ],
    mistakes: [
      'Using only the arms — the power comes from the middle.',
      'Going too fast on the way back.',
    ],
    safety: 'Keep knees soft. If your lower back complains, raise the cable and lighten the weight.',
    video: 'https://www.youtube.com/watch?v=he4IhLc1d5k',
    defaults: { sets: 3, reps: 10, weight: 25 },
    unit: 'lb',
  },
  dead_bug: {
    key: 'dead_bug',
    name: 'Dead Bug',
    quip: 'Named after a bug. Performed by a legend.',
    equipment: 'bodyweight',
    muscles: ['core'],
    cues: [
      'Lie on your back, arms pointing at the ceiling, knees up at 90 degrees.',
      'Press your lower back gently into the floor.',
      'Lower your RIGHT arm and LEFT leg toward the floor. Slowly.',
      'Come back. Switch sides. That is one rep.',
    ],
    mistakes: [
      'Letting the lower back arch off the floor.',
      'Holding your breath — keep breathing.',
    ],
    safety: 'If the floor is a long way down today, do it on a bench instead.',
    video: 'https://www.youtube.com/watch?v=bxn9FBrt4-A',
    defaults: { sets: 3, reps: 10, weight: null },
    unit: null,
  },
  pallof_press: {
    key: 'pallof_press',
    name: 'Pallof Press',
    quip: 'The goal is to not move. Finally, an exercise that plays to your strengths.',
    equipment: 'cable',
    muscles: ['core', 'obliques'],
    cues: [
      'Set the cable handle at chest height.',
      'Stand sideways to the machine, feet shoulder width apart.',
      'Hold the handle at your chest with both hands.',
      'Press your arms straight out in front of you. The cable will try to twist you. Refuse.',
      'Bring it back to your chest. That is one rep.',
    ],
    mistakes: [
      'Letting the shoulders twist toward the machine.',
      'Leaning away from the machine instead of standing tall.',
    ],
    safety: 'If you feel wobbly, stagger your stance slightly or stand closer to the machine for less pull.',
    video: 'https://www.youtube.com/watch?v=HXrLaqNIkTs',
    defaults: { sets: 3, reps: 10, weight: 15 },
    unit: 'lb',
  },
  bird_dog: {
    key: 'bird_dog',
    name: 'Bird Dog',
    quip: 'Point like a hunting dog. Wobble like a person. Both are fine.',
    equipment: 'bodyweight',
    muscles: ['core', 'lower back', 'glutes'],
    cues: [
      'Get on hands and knees. Hands under shoulders, knees under hips.',
      'Reach your RIGHT arm forward and your LEFT leg back. Slowly.',
      'Keep your hips level — imagine a cup of coffee balanced on your back.',
      'Hold for a breath. Come back. Switch sides.',
    ],
    mistakes: [
      'Lifting the leg so high the back arches.',
      'Rushing — this one rewards patience.',
    ],
    safety: 'Knees tender? Fold a towel under them, or do the arm-only version standing at a counter.',
    video: 'https://www.youtube.com/watch?v=ZdAHe9_HeEw',
    defaults: { sets: 3, reps: 8, weight: null },
    unit: null,
  },
  side_plank: {
    key: 'side_plank',
    name: 'Side Plank',
    quip: 'Lie on your side and refuse to fall over. That is the whole job.',
    equipment: 'bodyweight',
    muscles: ['core', 'obliques'],
    cues: [
      'Lie on your side, elbow under your shoulder, knees bent.',
      'Lift your hips so your body makes a straight line from head to knees.',
      'Hold. Breathe. Do not negotiate with the floor.',
      'Lower down with control. Then the other side.',
    ],
    mistakes: [
      'Letting the hips sag toward the floor.',
      'Shoulder creeping up toward the ear.',
    ],
    safety: 'The bent-knee version shown here is the right version. Straight legs can wait forever.',
    video: 'https://www.youtube.com/watch?v=44ND4bOB-T0',
    defaults: { sets: 3, reps: 20, weight: null },
    unit: 'seconds',
  },
  plank: {
    key: 'plank',
    name: 'Plank',
    quip: 'Do nothing, heroically.',
    equipment: 'bodyweight',
    muscles: ['core', 'shoulders'],
    cues: [
      'Forearms down, elbows under shoulders, legs stretched behind you.',
      'Make one straight line from head to heels.',
      'Squeeze your stomach and your rear like you mean it.',
      'Breathe normally. Watch the clock, not the floor.',
    ],
    mistakes: [
      'Hips sagging — that is a nap, not a plank.',
      'Hips too high — that is a tent, not a plank.',
      'Holding your breath.',
    ],
    safety: 'Forearms on a bench or counter instead of the floor if getting down is a chore.',
    video: 'https://www.youtube.com/watch?v=mH5Sfb_KTGg',
    defaults: { sets: 3, reps: 30, weight: null },
    unit: 'seconds',
  },
  cable_crunch: {
    key: 'cable_crunch',
    name: 'Standing Cable Crunch',
    quip: 'A sit-up you do standing up. Civilization advances.',
    equipment: 'cable',
    muscles: ['core', 'abs'],
    cues: [
      'Set the rope on the high pulley. Face the machine and hold an end at each shoulder.',
      'Step back so the cable is taut. Feet shoulder width.',
      'Curl your ribs down toward your hips — like closing a book.',
      'Stand back up tall with control. That is one rep.',
    ],
    mistakes: [
      'Bowing from the hips instead of curling the trunk.',
      'Yanking with the arms — they only hold the rope.',
    ],
    safety: 'Keep the weight modest and the movement smooth. This is a squeeze, not a bow to the audience. If you have ever been told your bones are thinning, skip this one and do the Pallof Press instead.',
    video: 'https://www.youtube.com/watch?v=ij3lWMnoFzA',
    defaults: { sets: 3, reps: 12, weight: 30 },
    unit: 'lb',
  },
  standing_oblique_cable_crunch: {
    key: 'standing_oblique_cable_crunch',
    name: 'Standing Oblique Cable Crunch',
    quip: 'Like reaching into your pocket, if your pocket fought back.',
    equipment: 'cable',
    muscles: ['core', 'obliques'],
    cues: [
      'Set the handle on the high pulley. Stand sideways to the machine.',
      'Hold the handle with the hand nearest the machine, arm bent.',
      'Bend sideways away from the machine — bring your ribs toward your hip.',
      'Come back up slowly. Finish the set, then switch sides.',
    ],
    mistakes: [
      'Leaning forward or backward — this is a straight sideways bend.',
      'Letting the weight stack yank you back up.',
    ],
    safety: 'Light weight, tall posture. If your side complains beyond a good muscle burn, go lighter. If you have ever been told your bones are thinning, skip this one and do the Pallof Press instead.',
    video: 'https://www.youtube.com/watch?v=g8YWFMSJFIc',
    defaults: { sets: 3, reps: 10, weight: 15 },
    unit: 'lb',
  },
  farmer_carry: {
    key: 'farmer_carry',
    name: 'Farmer Carry',
    quip: 'Pick things up and walk around. Farmers have known this for centuries.',
    equipment: 'kettlebell',
    muscles: ['core', 'grip', 'shoulders'],
    cues: [
      'Stand between two kettlebells.',
      'Bend your knees, grab both, and stand up tall.',
      'Walk with steady, normal steps. Chest up, eyes forward.',
      'Set them down with bent knees, not a bent back.',
    ],
    mistakes: [
      'Leaning to one side — stay level, like carrying groceries you like.',
      'Tiny shuffling steps. Walk like you own the gym.',
    ],
    safety: 'Pick a clear path before you lift. If your grip gives out early, use lighter bells, not looser fingers.',
    video: 'https://www.youtube.com/watch?v=lLAw6fUccKA',
    defaults: { sets: 3, reps: 40, weight: null },
    unit: 'steps',
  },
  suitcase_carry: {
    key: 'suitcase_carry',
    name: 'Suitcase Carry',
    quip: 'Like the airport, but on purpose.',
    equipment: 'kettlebell',
    muscles: ['core', 'obliques', 'grip'],
    cues: [
      'Pick up ONE kettlebell like a suitcase.',
      'Stand tall. Do not lean toward the bell or away from it.',
      'Walk 20 steady steps, switch hands, walk back. That is one set.',
    ],
    mistakes: [
      'Leaning away from the weight — the whole point is staying straight.',
      'Shrugging the carrying shoulder up to your ear.',
    ],
    safety: 'This one works your sides hard with modest weight. No need to be brave with the bell size.',
    video: 'https://www.youtube.com/watch?v=WhxtwWqb2BQ',
    defaults: { sets: 3, reps: 40, weight: null },
    unit: 'steps',
  },
  glute_bridge: {
    key: 'glute_bridge',
    name: 'Glute Bridge',
    quip: 'Lift your hips. Lower your hips. Accept the applause.',
    equipment: 'bodyweight',
    muscles: ['glutes', 'core', 'hamstrings'],
    cues: [
      'Lie on your back, knees bent, feet flat and hip width apart.',
      'Push through your heels and lift your hips toward the ceiling.',
      'Squeeze your rear at the top. Straight line from knees to shoulders.',
      'Lower down slowly. That is one rep.',
    ],
    mistakes: [
      'Pushing so high the lower back arches.',
      'Letting the knees fall out or cave in.',
    ],
    safety: 'If getting to the floor is not on the menu today, squeeze-and-hold standing glute squeezes still count.',
    video: 'https://www.youtube.com/watch?v=nbjJjSa0cKo',
    defaults: { sets: 3, reps: 10, weight: null },
    unit: null,
  },
  kb_halo: {
    key: 'kb_halo',
    name: 'Kettlebell Halo',
    quip: 'A halo, earned the hard way.',
    equipment: 'kettlebell',
    muscles: ['core', 'shoulders'],
    cues: [
      'Hold a light kettlebell upside down by the horns at chest height.',
      'Circle it slowly around your head, close to the skull.',
      'Keep your trunk still — the arms travel, the body does not.',
      'One circle each direction is one rep.',
    ],
    mistakes: [
      'Swaying the hips along with the bell.',
      'Circling so fast you part your own hair.',
    ],
    safety: 'Ten pounds is plenty. If your shoulders dislike the circle, shrink it or halo a light dumbbell instead.',
    video: 'https://www.youtube.com/watch?v=Sci3lijQBmk',
    defaults: { sets: 3, reps: 8, weight: 10 },
    unit: 'lb',
  },
  seated_knee_lift: {
    key: 'seated_knee_lift',
    name: 'Seated Knee Lift',
    quip: 'Chair required. Excuses optional.',
    equipment: 'bodyweight',
    muscles: ['core', 'hip flexors'],
    cues: [
      'Sit tall on the edge of a bench, hands gripping the sides.',
      'Lean back slightly and brace your stomach.',
      'Lift both knees toward your chest.',
      'Lower your feet slowly — do not let them crash down.',
    ],
    mistakes: [
      'Slumping the back — tall and proud, even leaning.',
      'Dropping the feet instead of lowering them.',
    ],
    safety: 'One knee at a time is the friendly version. Same muscles, half the drama.',
    video: 'https://www.youtube.com/watch?v=GXPCSeFYJPI',
    defaults: { sets: 3, reps: 10, weight: null },
    unit: null,
  },
  cable_pull_through: {
    key: 'cable_pull_through',
    name: 'Cable Pull-Through',
    quip: 'Undignified to watch. Extremely effective.',
    equipment: 'cable',
    muscles: ['glutes', 'hamstrings', 'core'],
    cues: [
      'Set the rope on the low pulley. Face away and hold it between your legs.',
      'Walk forward until the cable is taut. Feet shoulder width.',
      'Push your hips BACK, chest proud, knees soft — like closing a car door with your rear.',
      'Stand up tall by squeezing your glutes. Arms just hold the rope.',
    ],
    mistakes: [
      'Bending the back instead of pushing the hips back.',
      'Pulling with the arms — they are rope holders, nothing more.',
    ],
    safety: 'This teaches the hip hinge with the weight behind you, which your spine appreciates. Keep it smooth.',
    video: 'https://www.youtube.com/watch?v=yXopOhzEoeo',
    defaults: { sets: 3, reps: 10, weight: 30 },
    unit: 'lb',
  },
  reverse_wood_chop: {
    key: 'reverse_wood_chop',
    name: 'Reverse Wood Chop',
    quip: 'The wood chop’s optimistic cousin. Everything is looking up.',
    equipment: 'cable',
    muscles: ['core', 'obliques', 'shoulders'],
    cues: [
      'Set the handle on the LOW pulley. Stand sideways to the machine, feet wide.',
      'Hold the handle with both hands near the low hip.',
      'Pull it up and across your body, finishing above the opposite shoulder.',
      'Hips and shoulders turn together. Lower it back slowly.',
    ],
    mistakes: [
      'Lifting with just the arms — the turn does the work.',
      'Letting the weight drop on the way down.',
    ],
    safety: 'Keep knees soft and the finish no higher than feels smooth. Shoulder grumbles mean finish at chest height.',
    video: 'https://www.youtube.com/watch?v=rHfjG2Oflz0',
    defaults: { sets: 3, reps: 10, weight: 20 },
    unit: 'lb',
  },
  db_side_bend: {
    key: 'db_side_bend',
    name: 'Dumbbell Side Bend',
    quip: 'Lean. Return. Repeat. A teapot with ambition.',
    equipment: 'dumbbell',
    muscles: ['core', 'obliques'],
    cues: [
      'Hold ONE dumbbell at your side. The other hand stays empty.',
      'Stand tall, feet hip width apart.',
      'Slide the weight down your leg by bending straight sideways.',
      'Pull yourself back up tall with the opposite side. Finish the set, then switch hands.',
    ],
    mistakes: [
      'Holding a weight in both hands — they cancel each other out.',
      'Leaning forward instead of straight sideways.',
    ],
    safety: 'Small range, tall posture. Your obliques do not need a deep bow to get the message.',
    video: 'https://www.youtube.com/watch?v=SAc_r42va6g',
    defaults: { sets: 3, reps: 12, weight: 20 },
    unit: 'lb',
  },
  wall_sit: {
    key: 'wall_sit',
    name: 'Wall Sit',
    quip: 'A chair made entirely of willpower.',
    equipment: 'bodyweight',
    muscles: ['quads', 'glutes', 'core'],
    cues: [
      'Back flat against a wall, feet out in front of you.',
      'Slide down until your knees are comfortably bent — no deeper than a chair.',
      'Press your back into the wall and hold.',
      'Breathe. Glaring at the clock is allowed.',
    ],
    mistakes: [
      'Sliding too deep — thighs level with the floor is the maximum, not the goal.',
      'Knees drifting past the toes; walk the feet out farther.',
    ],
    safety: 'Stay well above parallel if your knees have opinions. A shallow wall sit is still a wall sit.',
    video: 'https://www.youtube.com/watch?v=sT0jUNnb9dk',
    defaults: { sets: 3, reps: 30, weight: null },
    unit: 'seconds',
  },
  single_leg_stand: {
    key: 'single_leg_stand',
    name: 'Single-Leg Stand',
    quip: 'The flamingo makes it look easy. The flamingo practices.',
    equipment: 'bodyweight',
    muscles: ['core', 'balance', 'ankles'],
    cues: [
      'Stand next to a counter or rack, fingertips resting on it.',
      'Lift one foot a few inches off the floor.',
      'Stand tall and hold. Eyes on a spot straight ahead.',
      'When it gets easy, hover the fingertips instead of resting them.',
      'Do both legs each set.',
    ],
    mistakes: [
      'Death-gripping the counter — fingertips only.',
      'Looking down at your feet. They know what they are doing.',
    ],
    safety: 'Always within reach of something sturdy. Balance improves fast, but the floor never softens.',
    video: 'https://www.youtube.com/watch?v=t5Mnjb3tvEc',
    defaults: { sets: 3, reps: 20, weight: null },
    unit: 'seconds',
  },
  // ---------------- CABLE ----------------
  face_pull: {
    key: 'face_pull',
    name: 'Face Pull',
    quip: 'For posture that says retired general, not retired question mark.',
    equipment: 'cable',
    muscles: ['rear shoulders', 'upper back'],
    cues: [
      'Set the rope at face height. Grab an end in each hand, palms facing in.',
      'Step back until the cable is taut.',
      'Pull the rope toward your face, elbows high and wide.',
      'Finish like you are showing off both biceps. Return slowly.',
    ],
    mistakes: [
      'Turning it into a row — the elbows should travel high, not tuck low.',
      'Leaning back and using bodyweight instead of muscle.',
    ],
    safety: 'Light weight, high reps. This one pays you in posture, not in bragging numbers.',
    video: 'https://www.youtube.com/watch?v=3pToT5_DUiY',
    defaults: { sets: 3, reps: 12, weight: 20 },
    unit: 'lb',
  },
  cable_chest_press: {
    key: 'cable_chest_press',
    name: 'Standing Cable Chest Press',
    quip: 'A push-up you perform standing up, like a gentleman.',
    equipment: 'cable',
    muscles: ['chest', 'triceps', 'core'],
    cues: [
      'Set both handles at chest height. Face away from the machine, one handle in each hand.',
      'Stagger your feet, one in front of the other, for balance.',
      'Press both handles straight forward until your arms are long.',
      'Return slowly. Your trunk stays still the whole time.',
    ],
    mistakes: [
      'Feet side by side — the cables will rock you backward.',
      'Letting the handles fly back instead of controlling them.',
    ],
    safety: 'The weight shown is per side. If balance feels iffy, do one arm at a time with a hand on the frame.',
    video: 'https://www.youtube.com/watch?v=fOHouR0t9Cw',
    defaults: { sets: 3, reps: 10, weight: 20 },
    unit: 'lb',
  },
  triceps_pushdown: {
    key: 'triceps_pushdown',
    name: 'Triceps Pushdown',
    quip: 'Wave goodbye with confidence.',
    equipment: 'cable',
    muscles: ['triceps'],
    cues: [
      'Set the bar or rope on the high pulley. Grab it with both hands.',
      'Pin your elbows to your sides. They live there now.',
      'Push down until your arms are straight.',
      'Let it rise slowly to chest height. Elbows never move.',
    ],
    mistakes: [
      'Elbows drifting forward — that turns it into a shove.',
      'Leaning your whole body onto the bar.',
    ],
    safety: 'The rope is gentler on the wrists than the straight bar. Take the gentle option; it is the same muscle.',
    video: 'https://www.youtube.com/watch?v=GCa8Q4e7laU',
    defaults: { sets: 3, reps: 12, weight: 25 },
    unit: 'lb',
  },
  biceps_cable_curl: {
    key: 'biceps_cable_curl',
    name: 'Cable Biceps Curl',
    quip: 'The beach is a state of mind.',
    equipment: 'cable',
    muscles: ['biceps'],
    cues: [
      'Set the bar on the low pulley. Grab it palms up.',
      'Stand tall, elbows tucked at your sides.',
      'Curl the bar to your chest. Elbows stay put.',
      'Lower slowly — the way down builds as much as the way up.',
    ],
    mistakes: [
      'Rocking the body to swing the weight up.',
      'Dropping the bar instead of lowering it.',
    ],
    safety: 'Wrists complaining? Use the rope with palms facing each other. Same biceps, happier wrists.',
    video: 'https://www.youtube.com/watch?v=nHAWuGPI0OI',
    defaults: { sets: 3, reps: 10, weight: 20 },
    unit: 'lb',
  },
  straight_arm_pulldown: {
    key: 'straight_arm_pulldown',
    name: 'Straight-Arm Pulldown',
    quip: 'For lats. Yes, you have lats.',
    equipment: 'cable',
    muscles: ['lats', 'core'],
    cues: [
      'Set the bar or rope on the high pulley. Face the machine.',
      'Hold it at shoulder height, arms long, slight bend in the elbows.',
      'Sweep your hands down to your thighs in one smooth arc.',
      'Let them rise slowly back up. The elbows never bend more.',
    ],
    mistakes: [
      'Bending the elbows — that steals the work for the triceps.',
      'Hunching forward as the bar comes down. Stay tall.',
    ],
    safety: 'Stop the top of the arc wherever your shoulders feel smooth. No prizes for extra height.',
    video: 'https://www.youtube.com/watch?v=mvgQs3CkgGQ',
    defaults: { sets: 3, reps: 12, weight: 25 },
    unit: 'lb',
  },
  // ---------------- KETTLEBELL ----------------
  goblet_squat: {
    key: 'goblet_squat',
    name: 'Goblet Squat',
    quip: 'Hold the bell like a bowl of soup you refuse to spill.',
    equipment: 'kettlebell',
    muscles: ['quads', 'glutes', 'core'],
    cues: [
      'Hold the kettlebell at your chest with both hands, elbows down.',
      'Feet a bit wider than shoulders, toes turned out slightly.',
      'Sit down between your heels — as deep as feels smooth.',
      'Push the floor away to stand. Chest stays proud throughout.',
    ],
    mistakes: [
      'Knees caving inward — push them out over the toes.',
      'Heels lifting off the floor.',
      'Letting the bell drag the chest down.',
    ],
    safety: 'Depth is negotiable, form is not. Squatting to a bench behind you is a fine version, not a lesser one.',
    video: 'https://www.youtube.com/watch?v=MeIiIdhvXT4',
    defaults: { sets: 3, reps: 8, weight: 20 },
    unit: 'lb',
  },
  kb_deadlift: {
    key: 'kb_deadlift',
    name: 'Kettlebell Deadlift',
    quip: 'Pick it up. Put it down. The oldest exercise there is.',
    equipment: 'kettlebell',
    muscles: ['glutes', 'hamstrings', 'core'],
    cues: [
      'Stand over the bell, feet hip width, bell between your ankles.',
      'Push your hips back and bend your knees until you can grip the handle.',
      'Flatten your back, chest proud, arms straight.',
      'Stand up tall by driving through your heels. Squeeze at the top.',
      'Hinge back down the same way you came up.',
    ],
    mistakes: [
      'Rounding the back to reach the bell — hinge deeper instead.',
      'Yanking the bell off the floor. Squeeze it up.',
    ],
    safety: 'Set the bell on a low step to shorten the trip if the floor feels far. Your spine prefers a proud chest to a deep reach.',
    video: 'https://www.youtube.com/watch?v=MJPGkNqAXzg',
    defaults: { sets: 3, reps: 8, weight: 35 },
    unit: 'lb',
  },
  kb_swing_light: {
    key: 'kb_swing_light',
    name: 'Kettlebell Swing (Light)',
    quip: 'The hips do the work. The arms are just along for the ride.',
    equipment: 'kettlebell',
    muscles: ['glutes', 'hamstrings', 'core'],
    cues: [
      'Master the kettlebell deadlift first. The swing is that hinge, with rhythm.',
      'Hold a LIGHT bell with both hands, feet wide.',
      'Push your hips back, let the bell swing behind you — then snap the hips forward.',
      'The bell floats to chest height at most. No higher.',
      'Let it fall and hinge again. Stop the set while your form is still proud.',
    ],
    mistakes: [
      'Lifting with the arms and shoulders — the hips launch it.',
      'Squatting instead of hinging. Hips back, not down.',
      'Chasing height. Chest height is the ceiling.',
    ],
    safety: 'Keep it light and crisp, never heavy and heroic. Any back grumble means switch to kettlebell deadlifts — same muscles, no momentum. First time? Film a set and let your son see it before this becomes a habit.',
    video: 'https://www.youtube.com/watch?v=8GpQ66AAKU0',
    defaults: { sets: 3, reps: 10, weight: 20 },
    unit: 'lb',
  },
  kb_overhead_press: {
    key: 'kb_overhead_press',
    name: 'Kettlebell Overhead Press',
    quip: 'Press it up. Congratulations, you are taller now.',
    equipment: 'kettlebell',
    muscles: ['shoulders', 'triceps', 'core'],
    cues: [
      'Stand tall holding ONE bell at your shoulder, elbow tucked.',
      'Squeeze your stomach and your rear — that is your foundation.',
      'Press the bell straight up until your arm is long.',
      'Lower it back to the shoulder with control. Finish the set, then switch arms.',
    ],
    mistakes: [
      'Leaning back to sneak the weight up — stay stacked and tall.',
      'Pressing forward instead of straight overhead.',
    ],
    safety: 'If straight overhead pinches, press at a slight forward angle or switch to the dumbbell shoulder press. No shoulder is impressed by pain.',
    video: 'https://www.youtube.com/watch?v=gjr-QAdsq4o',
    defaults: { sets: 3, reps: 8, weight: 15 },
    unit: 'lb',
  },
  // ---------------- DUMBBELL ----------------
  db_bench_press: {
    key: 'db_bench_press',
    name: 'Dumbbell Bench Press',
    quip: 'The classic. Arnold approves.',
    equipment: 'dumbbell',
    muscles: ['chest', 'triceps', 'shoulders'],
    cues: [
      'Sit on the bench with the dumbbells resting on your thighs. The weight shown is per hand.',
      'Lie back and bring the weights to the sides of your chest.',
      'Press them up until your arms are long. Do not clank them together.',
      'Lower slowly to the chest. That is one rep.',
    ],
    mistakes: [
      'Flaring the elbows straight out — keep them at a comfortable angle.',
      'Bouncing the weights off the chest.',
    ],
    safety: 'Sit up by dropping the weights to your thighs first — never overhead. When in doubt, the machine chest press spots you automatically.',
    video: 'https://www.youtube.com/watch?v=Y_7aHqXeCfQ',
    defaults: { sets: 3, reps: 10, weight: 20 },
    unit: 'lb',
  },
  db_incline_press: {
    key: 'db_incline_press',
    name: 'Incline Dumbbell Press',
    quip: 'Bench press, but uphill. Character building.',
    equipment: 'dumbbell',
    muscles: ['upper chest', 'shoulders', 'triceps'],
    cues: [
      'Set the bench to a gentle incline — about 30 degrees.',
      'Weights start at the sides of your upper chest. The weight shown is per hand.',
      'Press up and slightly back until your arms are long.',
      'Lower with control. No bouncing at the bottom.',
    ],
    mistakes: [
      'Setting the bench too steep — that turns it into a shoulder press.',
      'Arching the back off the bench.',
    ],
    safety: 'Feet flat, back settled into the bench. Return the weights to your thighs before sitting up.',
    video: 'https://www.youtube.com/watch?v=hChjZQhX1Ls',
    defaults: { sets: 3, reps: 10, weight: 15 },
    unit: 'lb',
  },
  db_shoulder_press: {
    key: 'db_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    quip: 'Shoulders like a coat hanger. The good wooden kind.',
    equipment: 'dumbbell',
    muscles: ['shoulders', 'triceps'],
    cues: [
      'Sit tall on a bench with back support, a dumbbell at each shoulder. The weight shown is per hand.',
      'Palms face forward or slightly in, whichever feels smoother.',
      'Press both weights up until your arms are long.',
      'Lower back to the shoulders slowly.',
    ],
    mistakes: [
      'Arching the lower back to push the weights up.',
      'Clanking the dumbbells together at the top.',
    ],
    safety: 'The seated back-support version is the right call. If overhead pinches, stop the press just short of the top.',
    video: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
    defaults: { sets: 3, reps: 10, weight: 12 },
    unit: 'lb',
  },
  db_row: {
    key: 'db_row',
    name: 'One-Arm Dumbbell Row',
    quip: 'Start the lawnmower. The lawn is imaginary.',
    equipment: 'dumbbell',
    muscles: ['upper back', 'lats', 'biceps'],
    cues: [
      'Put your left hand and left knee on the bench. Right foot on the floor.',
      'Back flat as a table. Dumbbell hanging from your right hand.',
      'Pull the weight up to your hip — elbow sliding past your ribs.',
      'Lower slowly. Finish the set, then swap sides.',
    ],
    mistakes: [
      'Twisting the torso to heave the weight up.',
      'Shrugging instead of rowing — the elbow leads, not the shoulder.',
    ],
    safety: 'The bench takes the load off your lower back — lean on it with intent. Smooth pulls, no jerking.',
    video: 'https://www.youtube.com/watch?v=pYcpY20QaE8',
    defaults: { sets: 3, reps: 10, weight: 25 },
    unit: 'lb',
  },
  db_lateral_raise: {
    key: 'db_lateral_raise',
    name: 'Lateral Raise',
    quip: 'Light weights. Heavy dignity.',
    equipment: 'dumbbell',
    muscles: ['shoulders'],
    cues: [
      'Stand tall with a light dumbbell in each hand. The weight shown is per hand.',
      'Raise both arms out to the sides, elbows slightly bent.',
      'Stop at shoulder height, thumbs level with your pinkies — like slow wings.',
      'Lower slowly. Slower than you think.',
    ],
    mistakes: [
      'Swinging the weights up with a body heave.',
      'Lifting above shoulder height — nothing good lives up there.',
    ],
    safety: 'This is famously a light-weight exercise; heavy laterals only train bad habits. Sore shoulders? Raise to 45 degrees instead.',
    video: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    defaults: { sets: 3, reps: 12, weight: 8 },
    unit: 'lb',
  },
  db_curl: {
    key: 'db_curl',
    name: 'Dumbbell Curl',
    quip: 'For opening jars with unnecessary style.',
    equipment: 'dumbbell',
    muscles: ['biceps', 'forearms'],
    cues: [
      'Stand tall, a dumbbell in each hand at your sides. The weight shown is per hand.',
      'Curl both weights toward your shoulders. Elbows stay pinned to your ribs.',
      'Squeeze at the top like you mean it.',
      'Lower all the way down, slowly. Half reps build half arms.',
    ],
    mistakes: [
      'Swinging the back to lift the weight.',
      'Elbows drifting forward at the top.',
    ],
    safety: 'Hammer grip — palms facing each other — is kinder to cranky elbows and works just as well.',
    video: 'https://www.youtube.com/watch?v=XE_pHwbst04',
    defaults: { sets: 3, reps: 10, weight: 15 },
    unit: 'lb',
  },
  db_reverse_fly: {
    key: 'db_reverse_fly',
    name: 'Seated Reverse Fly',
    quip: 'The official un-huncher.',
    equipment: 'dumbbell',
    muscles: ['rear shoulders', 'upper back'],
    cues: [
      'Sit on the end of a bench, a light dumbbell in each hand. The weight shown is per hand.',
      'Lean forward from the hips, back flat, weights hanging under you.',
      'Raise both arms out to the sides like slow wings.',
      'Squeeze the shoulder blades together. Lower with control.',
    ],
    mistakes: [
      'Bouncing the torso to swing the weights.',
      'Rounding the back while leaning forward.',
    ],
    safety: 'Seated and braced beats standing and straining. If the lean bothers your back, do face pulls instead — same postural payoff.',
    video: 'https://www.youtube.com/watch?v=1jpBatm8RYw',
    defaults: { sets: 3, reps: 12, weight: 8 },
    unit: 'lb',
  },
  // ---------------- MACHINE ----------------
  leg_press: {
    key: 'leg_press',
    name: 'Leg Press',
    quip: 'All of the squatting, none of the falling.',
    equipment: 'machine',
    muscles: ['quads', 'glutes', 'hamstrings'],
    cues: [
      'Adjust the seat so your knees start around a right angle, and know where the stop handles are before your first rep.',
      'Sit back in the machine, feet on the platform shoulder width apart.',
      'Press until your legs are long — but keep a soft bend in the knees.',
      'Lower slowly until your knees make a right angle.',
      'Press back up. Breathe out on the push.',
    ],
    mistakes: [
      'Locking the knees hard at the top.',
      'Going so deep your lower back curls off the pad.',
      'Fast, bouncy reps.',
    ],
    safety: 'Your back stays glued to the pad the entire time. Shallower and heavier beats deeper and rounder.',
    video: 'https://www.youtube.com/watch?v=8nm863C0c60',
    defaults: { sets: 3, reps: 10, weight: 90 },
    unit: 'lb',
  },
  machine_chest_press: {
    key: 'machine_chest_press',
    name: 'Machine Chest Press',
    quip: 'The machine holds the path. You bring the push.',
    equipment: 'machine',
    muscles: ['chest', 'triceps', 'shoulders'],
    cues: [
      'Adjust the seat so the handles line up with the middle of your chest.',
      'Sit tall, back against the pad.',
      'Press the handles forward until your arms are long.',
      'Return slowly — do not let the stack slam.',
    ],
    mistakes: [
      'Seat too low or too high — the handles should meet your chest, not your chin.',
      'Half reps. Take the full comfortable range.',
    ],
    safety: 'The friendliest press in the gym — the machine cannot fall on you. Ideal on days the dumbbells feel ambitious.',
    video: 'https://www.youtube.com/watch?v=zgP-UCKGe24',
    defaults: { sets: 3, reps: 10, weight: 40 },
    unit: 'lb',
  },
  machine_seated_row: {
    key: 'machine_seated_row',
    name: 'Seated Row',
    quip: 'Rowing, minus the lake at six in the morning.',
    equipment: 'machine',
    muscles: ['upper back', 'lats', 'biceps'],
    cues: [
      'Sit with your chest against the pad, or tall if there is no pad.',
      'Grab the handles with arms long.',
      'Pull to your ribs — squeeze the shoulder blades together like cracking a walnut.',
      'Let the handles travel back slowly until your arms are long again.',
    ],
    mistakes: [
      'Rocking the whole body backward to move the weight.',
      'Shrugging the shoulders up toward the ears.',
    ],
    safety: 'Rows are money in the bank for posture. Keep the motion smooth and let the back muscles, not momentum, do the pulling.',
    video: 'https://www.youtube.com/watch?v=7BkgqzC6WsM',
    defaults: { sets: 3, reps: 10, weight: 50 },
    unit: 'lb',
  },
  lat_pulldown: {
    key: 'lat_pulldown',
    name: 'Lat Pulldown',
    quip: 'A pull-up for people with better judgment.',
    equipment: 'machine',
    muscles: ['lats', 'upper back', 'biceps'],
    cues: [
      'Grip the bar a bit wider than your shoulders. Sit with thighs under the pads.',
      'Lean back slightly — an inch, not a sunbath.',
      'Pull the bar down to the top of your chest.',
      'Let it rise slowly until your arms are long. Stay in your seat.',
    ],
    mistakes: [
      'Pulling the bar behind the neck — never worth it.',
      'Leaning way back and turning it into a row.',
    ],
    safety: 'Always to the front of the chest. If your shoulders grumble at the wide grip, bring the hands in.',
    video: 'https://www.youtube.com/watch?v=Z_3xHwuO8Tk',
    defaults: { sets: 3, reps: 10, weight: 50 },
    unit: 'lb',
  },
  // ---------------- BODYWEIGHT ----------------
  step_up: {
    key: 'step_up',
    name: 'Step-Up',
    quip: 'Stairs, but you win on purpose.',
    equipment: 'bodyweight',
    muscles: ['quads', 'glutes', 'balance'],
    cues: [
      'Stand facing a low, sturdy step or bench.',
      'Step up with your RIGHT foot and drive through that heel to stand on top.',
      'Step down slowly and with control.',
      'Do all reps on one leg, then switch. A hand on the rail is allowed.',
    ],
    mistakes: [
      'Pushing off the bottom foot — the top leg does the lifting.',
      'Dropping down instead of lowering down.',
    ],
    safety: 'Start with a low step and something to hold. Height can grow; a stumble helps nobody.',
    video: 'https://www.youtube.com/watch?v=vs87hPGdnCc',
    defaults: { sets: 3, reps: 8, weight: null },
    unit: null,
  },
  wall_pushup: {
    key: 'wall_pushup',
    name: 'Wall Push-Up',
    quip: 'The wall has never lost a match. Push anyway.',
    equipment: 'bodyweight',
    muscles: ['chest', 'triceps', 'core'],
    cues: [
      'Hands on the wall at shoulder height, feet a big step back.',
      'Body straight as a plank from head to heels.',
      'Bend the elbows and bring your nose toward the wall.',
      'Push back to straight arms. That is one rep.',
    ],
    mistakes: [
      'Hips sagging or sticking out — keep the plank.',
      'Standing too close, which turns it into a lean.',
    ],
    safety: 'Walk the feet closer for easier, farther for harder. The dial is yours.',
    video: 'https://www.youtube.com/watch?v=PkFu8ee6IuY',
    defaults: { sets: 3, reps: 12, weight: null },
    unit: null,
  },
  incline_pushup: {
    key: 'incline_pushup',
    name: 'Incline Push-Up',
    quip: 'A push-up with the difficulty dial set to reasonable.',
    equipment: 'bodyweight',
    muscles: ['chest', 'triceps', 'core'],
    cues: [
      'Hands on a sturdy bench or rack bar, arms straight.',
      'Walk your feet back until your body is one straight line.',
      'Lower your chest to the edge with control.',
      'Push back up. Keep your stomach braced the whole way.',
    ],
    mistakes: [
      'Leading with the chin instead of the chest.',
      'Letting the hips sag as you tire.',
    ],
    safety: 'Higher surface, easier rep — pick the height where the last rep is hard but handsome. Wall push-ups are the same move, gentler.',
    video: 'https://www.youtube.com/watch?v=0JUrOH--Kdk',
    defaults: { sets: 3, reps: 8, weight: null },
    unit: null,
  },
  chair_squat: {
    key: 'chair_squat',
    name: 'Chair Squat',
    quip: 'Sit down. Stand up. Now do it like you mean it.',
    equipment: 'bodyweight',
    muscles: ['quads', 'glutes', 'core'],
    cues: [
      'Stand in front of a bench or sturdy chair, feet shoulder width.',
      'Push your hips back and lower until you barely touch the seat.',
      'No sitting, no plopping — just a polite tap.',
      'Stand tall by pushing through your heels.',
    ],
    mistakes: [
      'Collapsing onto the seat and rocking back up.',
      'Knees caving inward on the way up.',
    ],
    safety: 'Arms reaching forward act as a counterweight. On a strong day, hold the tap for two seconds; on any day, actually sitting and standing again still counts.',
    video: 'https://www.youtube.com/watch?v=w2jbtOQ_bdM',
    defaults: { sets: 3, reps: 8, weight: null },
    unit: null,
  },
  calf_raise: {
    key: 'calf_raise',
    name: 'Calf Raise',
    quip: 'Tiptoe like you are sneaking dessert.',
    equipment: 'bodyweight',
    muscles: ['calves', 'ankles', 'balance'],
    cues: [
      'Stand tall with fingertips on a rail or wall for balance.',
      'Rise up onto the balls of both feet. Pause at the top.',
      'Lower your heels slowly all the way down.',
      'Up two seconds, down two seconds.',
    ],
    mistakes: [
      'Bouncing instead of pausing at the top.',
      'Rolling the ankles outward.',
    ],
    safety: 'Strong calves are ankle insurance. Keep the balance hand handy; the exercise works fine with it.',
    video: 'https://www.youtube.com/watch?v=SVtg-1loH4c',
    defaults: { sets: 3, reps: 12, weight: null },
    unit: null,
  },
  standing_march: {
    key: 'standing_march',
    name: 'Standing March',
    quip: 'Going nowhere, impressively.',
    equipment: 'bodyweight',
    muscles: ['core', 'hip flexors', 'balance'],
    cues: [
      'Stand tall, hands on hips or resting on a counter.',
      'Lift one knee to hip height — or as close as feels smooth.',
      'Lower it with control and lift the other. That is marching.',
      'Slow beats fast. Tall beats slouched.',
    ],
    mistakes: [
      'Leaning back to hoist the knee higher.',
      'Rushing — this is a march, not a sprint.',
    ],
    safety: 'A fine warm-up and a sneaky core drill. Stay near support until the balance feels boring.',
    video: 'https://www.youtube.com/watch?v=5euy_1A8uHQ',
    defaults: { sets: 3, reps: 30, weight: null },
    unit: 'steps',
  },
}
